# **folium**

In [27]:
import numpy as np
import pandas as pd
import json
import folium

print(f'numpy : {np.__version__}, pandas : {pd.__version__}, json:{json.__version__}, folium:{folium.__version__}')

numpy : 2.5.2, pandas : 3.0.5, json:2.0.9, folium:0.20.0

## 8. GeoJson을 할용한 경계 표현

- GeoJson : 행정구역과 같은 경계선이나 경로를 표현하는데 효율적

#### 1) 서울시 행정동 단위별 경계 표현

- 서울시 행정동별 지도 경계 표시 데이터 : geojson

In [4]:
with open('data/geojson/행정동_서울특별시.geojson', encoding='utf-8') as f:
    geo_seoul = json.loads(f.read())

- geojson 형식 파악

In [5]:
type(geo_seoul)

dict

In [7]:
geo_seoul.keys()

dict_keys(['type', 'name', 'crs', 'features'])

In [ ]:
type(geo_seoul).

In [12]:
geo_seoul['features'][0]

{'type': 'Feature',
 'properties': {'OBJECTID': 1,
  'adm_nm': '서울특별시 종로구 사직동',
  'adm_cd': '1101053',
  'adm_cd2': '1111053000',
  'sgg': '11110',
  'sido': '11',
  'sidonm': '서울특별시',
  'sggnm': '종로구'},
 'geometry': {'type': 'MultiPolygon',
  'coordinates': [[[[126.97688884274817, 37.575650779448786],
     [126.9770344988775, 37.56919453005455],
     [126.97597472821249, 37.569336299425764],
     [126.97537470991254, 37.56931556702156],
     [126.97433193562325, 37.56926180051753],
     [126.96904837001854, 37.568194417708334],
     [126.96854493603384, 37.56842767961276],
     [126.9666499598212, 37.56949165520658],
     [126.96628175024485, 37.5697007347987],
     [126.9660973270804, 37.5698565097237],
     [126.96572852922577, 37.570183936115114],
     [126.96592699822128, 37.5703188056862],
     [126.96601094018429, 37.571548395577466],
     [126.96365922052196, 37.57517466066037],
     [126.9630860043451, 37.57648592001554],
     [126.96284099051198, 37.57666158609274],
     [126.96281041047263, 37.579448809656775],
     [126.96742431584332, 37.57960153712449],
     [126.96742176302651, 37.579263521441646],
     [126.9674300601846, 37.579192577998604],
     [126.9674570900956, 37.57897525058544],
     [126.96806604699626, 37.57824678046787],
     [126.96895511695477, 37.57793526234028],
     [126.96921284296906, 37.57793529930939],
     [126.96941453886579, 37.578121124142164],
     [126.9696644266947, 37.57853113668221],
     [126.96966721914872, 37.57873620513493],
     [126.96966877353309, 37.57899287900988],
     [126.96966949910363, 37.57911252674959],
     [126.96990457361626, 37.579301753628734],
     [126.97135197544759, 37.57951327793981],
     [126.97381925784454, 37.57937214030263],
     [126.97391736338342, 37.57848707304101],
     [126.97393961998088, 37.57824042997809],
     [126.97433153835757, 37.57574990629986],
     [126.97580378997804, 37.5756494688242],
     [126.97688884274817, 37.575650779448786]]]]}}

In [10]:
geo_seoul['features'][0].keys()

dict_keys(['type', 'properties', 'geometry'])

In [13]:
geo_seoul['features'][0]['type']

'Feature'

In [14]:
geo_seoul['features'][0]['properties']

{'OBJECTID': 1,
 'adm_nm': '서울특별시 종로구 사직동',
 'adm_cd': '1101053',
 'adm_cd2': '1111053000',
 'sgg': '11110',
 'sido': '11',
 'sidonm': '서울특별시',
 'sggnm': '종로구'}

In [15]:
geo_seoul['features'][0]['geometry']

{'type': 'MultiPolygon',
 'coordinates': [[[[126.97688884274817, 37.575650779448786],
    [126.9770344988775, 37.56919453005455],
    [126.97597472821249, 37.569336299425764],
    [126.97537470991254, 37.56931556702156],
    [126.97433193562325, 37.56926180051753],
    [126.96904837001854, 37.568194417708334],
    [126.96854493603384, 37.56842767961276],
    [126.9666499598212, 37.56949165520658],
    [126.96628175024485, 37.5697007347987],
    [126.9660973270804, 37.5698565097237],
    [126.96572852922577, 37.570183936115114],
    [126.96592699822128, 37.5703188056862],
    [126.96601094018429, 37.571548395577466],
    [126.96365922052196, 37.57517466066037],
    [126.9630860043451, 37.57648592001554],
    [126.96284099051198, 37.57666158609274],
    [126.96281041047263, 37.579448809656775],
    [126.96742431584332, 37.57960153712449],
    [126.96742176302651, 37.579263521441646],
    [126.9674300601846, 37.579192577998604],
    [126.9674570900956, 37.57897525058544],
    [126.96806604699626, 37.57824678046787],
    [126.96895511695477, 37.57793526234028],
    [126.96921284296906, 37.57793529930939],
    [126.96941453886579, 37.578121124142164],
    [126.9696644266947, 37.57853113668221],
    [126.96966721914872, 37.57873620513493],
    [126.96966877353309, 37.57899287900988],
    [126.96966949910363, 37.57911252674959],
    [126.96990457361626, 37.579301753628734],
    [126.97135197544759, 37.57951327793981],
    [126.97381925784454, 37.57937214030263],
    [126.97391736338342, 37.57848707304101],
    [126.97393961998088, 37.57824042997809],
    [126.97433153835757, 37.57574990629986],
    [126.97580378997804, 37.5756494688242],
    [126.97688884274817, 37.575650779448786]]]]}

In [16]:
geo_seoul['features']

[{'type': 'Feature',
  'properties': {'OBJECTID': 1,
   'adm_nm': '서울특별시 종로구 사직동',
   'adm_cd': '1101053',
   'adm_cd2': '1111053000',
   'sgg': '11110',
   'sido': '11',
   'sidonm': '서울특별시',
   'sggnm': '종로구'},
  'geometry': {'type': 'MultiPolygon',
   'coordinates': [[[[126.97688884274817, 37.575650779448786],
      [126.9770344988775, 37.56919453005455],
      [126.97597472821249, 37.569336299425764],
      [126.97537470991254, 37.56931556702156],
      [126.97433193562325, 37.56926180051753],
      [126.96904837001854, 37.568194417708334],
      [126.96854493603384, 37.56842767961276],
      [126.9666499598212, 37.56949165520658],
      [126.96628175024485, 37.5697007347987],
      [126.9660973270804, 37.5698565097237],
      [126.96572852922577, 37.570183936115114],
      [126.96592699822128, 37.5703188056862],
      [126.96601094018429, 37.571548395577466],
      [126.96365922052196, 37.57517466066037],
      [126.9630860043451, 37.57648592001554],
      [126.96284099051198, 37.57666158609274],
      [126.96281041047263, 37.579448809656775],
      [126.96742431584332, 37.57960153712449],
      [126.96742176302651, 37.579263521441646],
      [126.9674300601846, 37.579192577998604],
      [126.9674570900956, 37.57897525058544],
      [126.96806604699626, 37.57824678046787],
      [126.96895511695477, 37.57793526234028],
      [126.96921284296906, 37.57793529930939],
      [126.96941453886579, 37.578121124142164],
      [126.9696644266947, 37.57853113668221],
      [126.96966721914872, 37.57873620513493],
      [126.96966877353309, 37.57899287900988],
      [126.96966949910363, 37.57911252674959],
      [126.96990457361626, 37.579301753628734],
      [126.97135197544759, 37.57951327793981],
      [126.97381925784454, 37.57937214030263],
      [126.97391736338342, 37.57848707304101],
      [126.97393961998088, 37.57824042997809],
      [126.97433153835757, 37.57574990629986],
      [126.97580378997804, 37.5756494688242],
      [126.97688884274817, 37.575650779448786]]]]}},
 {'type': 'Feature',
  'properties': {'OBJECTID': 2,
   'adm_nm': '서울특별시 종로구 삼청동',
   'adm_cd': '1101054',
   'adm_cd2': '1111054000',
   'sgg': '11110',
   'sido': '11',
   'sidonm': '서울특별시',
   'sggnm': '종로구'},
  'geometry': {'type': 'MultiPolygon',
   'coordinates': [[[[126.98268938649305, 37.5950655194224],
      [126.98337258456999, 37.59435192551688],
      [126.98386809792802, 37.59385046812643],
      [126.9840115836973, 37.59375538189762],
      [126.98427349619085, 37.593581837353476],
      [126.98467876724008, 37.593331231471026],
      [126.98522535985275, 37.5930571567418],
      [126.98528680814083, 37.593026356335294],
      [126.98532872580722, 37.59300572621492],
      [126.9857592771792, 37.59279401160435],
      [126.98647984078382, 37.59250646566557],
      [126.98752622820251, 37.592246800190104],
      [126.9887608091341, 37.59210400307576],
      [126.98910945071732, 37.591953415500925],
      [126.98947579208668, 37.5917950211998],
      [126.98907504810013, 37.59139446162827],
      [126.98789849580885, 37.59055671520521],
      [126.98621002796946, 37.58901596665143],
      [126.9860138742825, 37.58820164992095],
      [126.98601087423725, 37.588020241414476],
      [126.98595696428241, 37.587418359612826],
      [126.98579012895927, 37.58707512222899],
      [126.98533710003068, 37.586145890121195],
      [126.98497436228654, 37.58563328549674],
      [126.98446533234532, 37.585373689951126],
      [126.98371421781621, 37.5849704355389],
      [126.98291838651029, 37.58345832694683],
      [126.98284931592738, 37.58322799314753],
      [126.98283620716704, 37.58285406704333],
      [126.98284210401096, 37.582717763620884],
      [126.98286481989483, 37.5826063226581],
      [126.9829917870471, 37.58205705864078],
      [126.98403469536836, 37.57843370671978],
      [126.98463962427503, 37.57734234320301],
      [126.98553316382565, 37.576674025462005],
      [126.98494884418297, 37.57633588036589],
      [126.98434478868091, 37.5760645251064],
      [126.98314665239185, 37.57552636292861],
      [126.97983903605082, 37.575943353839534],
      [126.9795924891094, 37.57597727455633],
      [126.97960579128436, 37.57660704191863],
      [126.97961751615897, 37.57716144799569],
      [126.97968954034279, 37.57860955110071],
      [126.97974112529974, 37.579131431874536],
      [126.98002822496196, 37.58008699576901],
      [126.9803037016248, 37.58098617361973],
      [126.97941793890371, 37.58590023032471],
      [126.9789736688563, 37.587178178288674],
      [126.9788795757727, 37.58727127731592],
      [126.97656681181762, 37.58929695337158],
      [126.97615022517256, 37.589545227974334],
      [126.97569334351333, 37.58968403424009],
      [126.97363965976345, 37.59259411899388],
      [126.97358726355343, 37.593289023280704],
      [126.97585113775686, 37.59656422224409],
      [126.98105808767329, 37.59506510110589],
      [126.98268938649305, 37.5950655194224]]]]}},
 {'type': 'Feature',
  'properties': {'OBJECTID': 3,
   'adm_nm': '서울특별시 종로구 부암동',
   'adm_cd': '1101055',
   'adm_cd2': '1111055000',
   'sgg': '11110',
   'sido': '11',
   'sidonm': '서울특별시',
   'sggnm': '종로구'},
  'geometry': {'type': 'MultiPolygon',
   'coordinates': [[[[126.97585113775686, 37.59656422224409],
      [126.97358726355343, 37.593289023280704],
      [126.97193752649407, 37.5938857822259],
      [126.97154760196382, 37.593701308790735],
      [126.96984441311325, 37.593475095196254],
      [126.96892484394625, 37.59336392580811],
      [126.96887189227614, 37.593364914263915],
      [126.96877898326484, 37.59336665034414],
      [126.96870727402127, 37.59341836116727],
      [126.96864235289421, 37.59346518297949],
      [126.96853059868413, 37.59350459936502],
      [126.96847201317486, 37.59352525660245],
      [126.96813865294972, 37.59361163575197],
      [126.96804392436819, 37.59359205532072],
      [126.9664337494751, 37.59293244072924],
      [126.96468814573528, 37.59112072592575],
      [126.96457451385055, 37.59097261926832],
      [126.96411161383803, 37.58998139049233],
      [126.96413760526842, 37.58963500891115],
      [126.96414204211857, 37.58958033196943],
      [126.96424002171672, 37.589343047586304],
      [126.96423724410882, 37.58913797948431],
      [126.96411590996077, 37.5889785669954],
      [126.96342248723037, 37.58814167454556],
      [126.96317388302286, 37.58786338117127],
      [126.96223300535345, 37.58698592219034],
      [126.96203639678752, 37.58686814731631],
      [126.96197714399632, 37.58683265456152],
      [126.96171066793023, 37.58667821129155],
      [126.96050597525429, 37.58626372501299],
      [126.95968214656355, 37.586044761977305],
      [126.95946929878956, 37.58601224045007],
      [126.95931127025352, 37.58606121583167],
      [126.95917912366734, 37.586102172264646],
      [126.95886514945398, 37.585957645050044],
      [126.95804842695327, 37.58521114524582],
      [126.95780467132904, 37.58498834135819],
      [126.9577538691774, 37.584868680012],
      [126.95789532461893, 37.583811410465415],
      [126.95689400065469, 37.585420104684566],
      [126.95717223390321, 37.586467603189405],
      [126.9574735302318, 37.587601840353926],
      [126.95792906131354, 37.58879364348914],
      [126.95751460018826, 37.592672080333635],
      [126.95725016810263, 37.593144703750234],
      [126.95676576001068, 37.59401050981959],
      [126.95649870631067, 37.59470677017238],
      [126.95632914160304, 37.59514982247609],
      [126.9563125845426, 37.59547761011785],
      [126.95630928970395, 37.59554294220438],
      [126.95630345806644, 37.59566236563108],
      [126.95661265444572, 37.59653656214864],
      [126.95695401282785, 37.59762350150384],
      [126.95698339228615, 37.59771780881644],
      [126.9570418857109, 37.59790557493377],
      [126.95714563624348, 37.59824292846682],
      [126.95713537894363, 37.59838709587642],
      [126.95710041957898, 37.59845887110829],
      [126.9570548804556, 37.59855234702035],
      [126.95696712112876, 37.598613815826],
      [126.95688336261372, 37.598632921916845],
      [126.95673120842258, 37.598664651887326],
      [126.95635103787437, 37.5986606479587],
      [126.95621405477384, 37.59859548988152],
      [126.95612384303078, 37.598552566951696],
      [126.95612709831886, 37.598516212839],
      [126.95613231415989, 37.598457965171306],
      [126.95551757216754, 37.59848329764554],
      [126.95409326316125, 37.59855107881123],
      [126.95397415385781, 37.59866633211085],
      [126.95393567136749, 37.598703577745205],
      [126.9538258579366, 37.59881010385266],
      [126.95350853979318, 37.599118470914306],
      [126.9527493088157, 37.60040612359548],
      [126.95276271153092, 37.601281207225824],
      [126.95276524589123, 37.60144420027711],
      [126.95277718634692, 37.6022066815291],
      [126.95277963884381, 37.602258519073516],
      [126.95280198474563, 37.60269470558269],
      [126.95288195668485, 37.60278965850004],
      [126.95301214464615, 37.602868930049006],
      [126.95308145295435, 37.60291113744484],
      [126.9532010847255, 37.6030119658938],
      [126.95326483042025, 37.60320266846132],
      [126.95351266201463, 37.60426514533311],
      [126.9535364786087, 37.60449397067246],
      [126.95354043497194, 37.6045741622926],
      [126.9535426442699, 37.60461905925903],
      [126.953437334822, 37.60517402329218],
      [126.95337632124976, 37.60536628405079],
      [126.95385758425479, 37.60493035368017],
      [126.95401005455305, 37.60480149063461],
      [126.95423800327578, 37.604712410991084],
      [126.9546270514898, 37.60457224932783],
      [126.95815442648258, 37.60353167478216],
      [126.95824923030347, 37.6035422509929],
      [126.95842358280305, 37.60361741180495],
      [126.95862521702003, 37.60373776453215],
      [126.95872965842487, 37.60380561788104],
      [126.95909449579969, 37.604738150752624],
      [126.96001187834644, 37.60585550704167],
      [126.96107055279366, 37.60696894061422],
      [126.96153478748715, 37.60705899444457],
      [126.96163807081584, 37.60677892266332],
      [126.96165869780006, 37.6067134631965],
      [126.961671405343, 37.60667316816799],
      [126.96169603184708, 37.60659666659297],
      [126.96175865813083, 37.6064538644944],
      [126.96177331035057, 37.60642370037181],
      [126.96182909593873, 37.606308844630554],
      [126.96188941764679, 37.60619194547463],
      [126.96197414607438, 37.6060289638724],
      [126.96210038797602, 37.60580420428451],
      [126.9622284450716, 37.605622266485106],
      [126.9626983832081, 37.605064449288584],
      [126.96315919788589, 37.604185170623396],
      [126.96325548402316, 37.604002275910716],
      [126.96433173414684, 37.60331200595572],
      [126.96566403522499, 37.6013700234922],
      [126.96616030329533, 37.60088441844237],
      [126.96661124451094, 37.60059802814502],
      [126.96714586411994, 37.600292860429086],
      [126.97329548935387, 37.59882077525425],
      [126.97410306006903, 37.59797156471124],
      [126.97418689340091, 37.597609013814214],
      [126.97367515089334, 37.59710436897587],
      [126.97382894533715, 37.597029522256484],
      [126.97400551087482, 37.5969436001788],
      [126.97585113775686, 37.59656422224409]]]]}},
 {'type': 'Feature',
  'properties': {'OBJECTID': 4,
   'adm_nm': '서울특별시 종로구 평창동',
   'adm_cd': '1101056',
   'adm_cd2': '1111056000',
   'sgg': '11110',
   'sido': '11',
   'sidonm': '서울특별시',
   'sggnm': '종로구'},
  'geometry': {'type': 'MultiPolygon',
   'coordinates': [[[[126.97507466788086, 37.63138628651299],
      [126.97648554431467, 37.63008899733446],
      [126.97635458028533, 37.62927157938801],
      [126.97667206133512, 37.628844852765404],
      [126.97821335697138, 37.62843593611979],
      [126.97952403531336, 37.62920222934059],
      [126.98009231237339, 37.62927233505252],
      [126.98050819494199, 37.629054464968306],
      [126.98049687592524, 37.62864543417669],
      [126.98013297406834, 37.6283510868893],
      [126.97966645720429, 37.62797478525103],
      [126.97948350377727, 37.62716032283383],
      [126.97943770306833, 37.62695639142638],
      [126.97920868855883, 37.624571211532476],
      [126.98017111102541, 37.623552567336695],
      [126.9808700629808, 37.62275225912288],
      [126.98137361379459, 37.62173377522716],
      [126.98208449776982, 37.61992295343913],
      [126.98180053290709, 37.619305416285336],
      [126.982019193894, 37.61871274006239],
      [126.98280587465077, 37.6166936891581],
      [126.98324329383502, 37.61631929720404],
      [126.9839756453184, 37.61610167384227],
      [126.9845404034313, 37.6158716506272],
      [126.98534132186184, 37.61554542739917],
      [126.98669703273053, 37.61468379283732],
      [126.98706809277698, 37.61355197137193],
      [126.98695966068111, 37.61057482215976],
      [126.98677169878638, 37.610401056555325],
      [126.98627148445792, 37.60993863667942],
      [126.98599891423133, 37.60879838063663],
      [126.9859737283335, 37.60837689415818],
      [126.9859576470348, 37.608107548561335],
      [126.98590060366917, 37.60713611432764],
      [126.98619440532723, 37.60627838883232],
      [126.98658928177832, 37.605125556935],
      [126.98774119171668, 37.601215535765455],
      [126.98637468543951, 37.60007953917752],
      [126.98490852653961, 37.5994388299471],
      [126.98289737359873, 37.599392692790644],
      [126.98272390667428, 37.59938871484209],
      [126.98267369503064, 37.599378355563736],
      [126.98222759868916, 37.59928401269243],
      [126.98156656448, 37.59914365527767],
      [126.98156645105354, 37.59803838498008],
      [126.98156684734501, 37.59716526193013],
      [126.98201142589032, 37.595843316832955],
      [126.98219342381577, 37.59563342662803],
      [126.98235011484135, 37.59545290805664],
      [126.98265231541407, 37.59510477354859],
      [126.98268938649305, 37.5950655194224],
      [126.98105808767329, 37.59506510110589],
      [126.97585113775686, 37.59656422224409],
      [126.97400551087482, 37.5969436001788],
      [126.97382894533715, 37.597029522256484],
      [126.97367515089334, 37.59710436897587],
      [126.97418689340091, 37.597609013814214],
      [126.97410306006903, 37.59797156471124],
      [126.97329548935387, 37.59882077525425],
      [126.96714586411994, 37.600292860429086],
      [126.96661124451094, 37.60059802814502],
      [126.96616030329533, 37.60088441844237],
      [126.96566403522499, 37.6013700234922],
      [126.96433173414684, 37.60331200595572],
      [126.96325548402316, 37.604002275910716],
      [126.96315919788589, 37.604185170623396],
      [126.9626983832081, 37.605064449288584],
      [126.9622284450716, 37.605622266485106],
      [126.96210038797602, 37.60580420428451],
      [126.96197414607438, 37.6060289638724],
      [126.96188941764679, 37.60619194547463],
      [126.96182909593873, 37.606308844630554],
      [126.96177331035057, 37.60642370037181],
      [126.96175865813083, 37.6064538644944],
      [126.96169603184708, 37.60659666659297],
      [126.961671405343, 37.60667316816799],
      [126.96165869780006, 37.6067134631965],
      [126.96163807081584, 37.60677892266332],
      [126.96153478748715, 37.60705899444457],
      [126.96107055279366, 37.60696894061422],
      [126.96001187834644, 37.60585550704167],
      [126.95909449579969, 37.604738150752624],
      [126.95872965842487, 37.60380561788104],
      [126.95862521702003, 37.60373776453215],
      [126.95842358280305, 37.60361741180495],
      [126.95824923030347, 37.6035422509929],
      [126.95815442648258, 37.60353167478216],
      [126.9546270514898, 37.60457224932783],
      [126.95423800327578, 37.604712410991084],
      [126.95401005455305, 37.60480149063461],
      [126.95385758425479, 37.60493035368017],
      [126.95337632124976, 37.60536628405079],
      [126.95312126377212, 37.605597315507204],
      [126.9507368785767, 37.608320203595696],
      [126.95037704631463, 37.6078785962168],
      [126.94998323286886, 37.60970523279793],
      [126.95063381638597, 37.61096446042616],
      [126.95084661235094, 37.611800361136716],
      [126.95093667782756, 37.61235961031376],
      [126.95069219565536, 37.614886725539854],
      [126.95039624404842, 37.61612806862719],
      [126.95033164260869, 37.618361960313514],
      [126.95124098574176, 37.62279288595064],
      [126.95171633967342, 37.624328550490226],
      [126.95217160172545, 37.62482296632809],
      [126.95235097425176, 37.62489477927635],
      [126.95317835565287, 37.62516676336979],
      [126.95675296135069, 37.62536579675912],
      [126.95747698489457, 37.626174869191146],
      [126.95954222807589, 37.62848258383034],
      [126.9623416153841, 37.628850275537076],
      [126.96762934018564, 37.629809389221364],
      [126.96834197582992, 37.62998532567903],
      [126.96881934584482, 37.63010318034924],
      [126.96925198582099, 37.63022341331836],
      [126.97020368282598, 37.630860893108554],
      [126.97178590780638, 37.63228533903874],
      [126.97507466788086, 37.63138628651299]]]]}},
 {'type': 'Feature',
  'properties': {'OBJECTID': 5,
   'adm_nm': '서울특별시 종로구 무악동',
   'adm_cd': '1101057',
   'adm_cd2': '1111057000',
   'sgg': '11110',
   'sido': '11',
   'sidonm': '서울특별시',
   'sggnm': '종로구'},
  'geometry': {'type': 'MultiPolygon',
   'coordinates': [[[[126.96067353273895, 37.58079784202973],
      [126.96281041047263, 37.579448809656775],
      [126.96284099051198, 37.57666158609274],
      [126.96178383085044, 37.57513908653102],
      [126.9606917293308, 37.57322005562149],
      [126.96041454461106, 37.57302985172071],
      [126.9595707378107, 37.572961218450786],
      [126.95392395620553, 37.578490716235244],
      [126.95355601666945, 37.57887566580948],
      [126.95416175053352, 37.57889874854087],
      [126.9548098422277, 37.578924817970716],
      [126.95495287262696, 37.57893057107095],
      [126.95545514457034, 37.57897006960424],
      [126.95555710960068, 37.57908687190313],
      [126.95574645955674, 37.57930378371988],
      [126.95576855122015, 37.58002395123693],
      [126.95576933368164, 37.5800494854105],
      [126.95579483992938, 37.58072925682743],
      [126.9564576046438, 37.58128325688558],
      [126.95700188847026, 37.58158320532254],
      [126.9571248221667, 37.581615317794835],
      [126.95826882631235, 37.58169718780315],
      [126.95877706184434, 37.581618172910275],
      [126.96067353273895, 37.58079784202973]]]]}},
 {'type': 'Feature',
  'properties': {'OBJECTID': 6,
   'adm_nm': '서울특별시 종로구 교남동',
   'adm_cd': '1101058',
   'adm_cd2': '1111058000',
   'sgg': '11110',
   'sido': '11',
   'sidonm': '서울특별시',
   'sggnm': '종로구'},
  'geometry': {'type': 'MultiPolygon',
   'coordinates': [[[[126.96904837001854, 37.568194417708334],
      [126.96801027119919, 37.56718251422151],
      [126.96792521742005, 37.56709695369099],
      [126.96733567672948, 37.56650376640693],
      [126.96729746629627, 37.56646554636408],
      [126.96719305150863, 37.56636085699477],
      [126.96713423029, 37.56630119278387],
      [126.96718646998274, 37.566255827643815],
      [126.96677353826367, 37.56579436403003],
      [126.9658121875202, 37.56666901462727],
      [126.96189826008306, 37.57065058360019],
      [126.9595707378107, 37.572961218450786],
      [126.96041454461106, 37.57302985172071],
      [126.9606917293308, 37.57322005562149],
      [126.96178383085044, 37.57513908653102],
      [126.96284099051198, 37.57666158609274],
      [126.9630860043451, 37.57648592001554],
      [126.96365922052196, 37.57517466066037],
      [126.96601094018429, 37.571548395577466],
      [126.96592699822128, 37.5703188056862],
      [126.96572852922577, 37.570183936115114],
      [126.9660973270804, 37.5698565097237],
      [126.96628175024485, 37.5697007347987],
      [126.9666499598212, 37.56949165520658],
      [126.96854493603384, 37.56842767961276],
      [126.96904837001854, 37.568194417708334]]]]}},

- 서울시 행정동별 지도 properties 속성을 데이터프레임으로 저장

In [17]:
pd.DataFrame(geo_seoul['features'])

,type,properties,geometry
0,Feature,"{'OBJECTID': 1, 'adm_nm': '서울특별시 종로구 사직동', 'ad...","{'type': 'MultiPolygon', 'coordinates': [[[[12..."
1,Feature,"{'OBJECTID': 2, 'adm_nm': '서울특별시 종로구 삼청동', 'ad...","{'type': 'MultiPolygon', 'coordinates': [[[[12..."
2,Feature,"{'OBJECTID': 3, 'adm_nm': '서울특별시 종로구 부암동', 'ad...","{'type': 'MultiPolygon', 'coordinates': [[[[12..."
3,Feature,"{'OBJECTID': 4, 'adm_nm': '서울특별시 종로구 평창동', 'ad...","{'type': 'MultiPolygon', 'coordinates': [[[[12..."
4,Feature,"{'OBJECTID': 5, 'adm_nm': '서울특별시 종로구 무악동', 'ad...","{'type': 'MultiPolygon', 'coordinates': [[[[12..."
...,...,...,...
420,Feature,"{'OBJECTID': 421, 'adm_nm': '서울특별시 강동구 둔촌2동', ...","{'type': 'MultiPolygon', 'coordinates': [[[[12..."
421,Feature,"{'OBJECTID': 422, 'adm_nm': '서울특별시 강동구 암사1동', ...","{'type': 'MultiPolygon', 'coordinates': [[[[12..."
422,Feature,"{'OBJECTID': 423, 'adm_nm': '서울특별시 강동구 천호2동', ...","{'type': 'MultiPolygon', 'coordinates': [[[[12..."
423,Feature,"{'OBJECTID': 424, 'adm_nm': '서울특별시 강동구 길동', 'a...","{'type': 'MultiPolygon', 'coordinates': [[[[12..."
424,Feature,"{'OBJECTID': 3479, 'adm_nm': '서울특별시 구로구 오류2동',...","{'type': 'MultiPolygon', 'coordinates': [[[[12..."

In [21]:
geo_seoul_prop_df = pd.DataFrame(dong['properties'] for dong in geo_seoul['features'])

In [22]:
geo_seoul_prop_df.tail()

     OBJECTID          adm_nm   adm_cd     adm_cd2    sgg sido sidonm sggnm
420       421  서울특별시 강동구 둔촌2동  1125071  1174070000  11740   11  서울특별시   강동구
421       422  서울특별시 강동구 암사1동  1125072  1174057000  11740   11  서울특별시   강동구
422       423  서울특별시 강동구 천호2동  1125073  1174061000  11740   11  서울특별시   강동구
423       424    서울특별시 강동구 길동  1125074  1174068500  11740   11  서울특별시   강동구
424      3479  서울특별시 구로구 오류2동  1117073  1153078000  11530   11  서울특별시   구로구

- 서울시 행정동별 지도경계선 표시

In [23]:
cityhall = (37.566535, 126.9779691999996)  # 서울 시청
zoom = 10
m = folium.Map(location=cityhall, zoom_start=zoom)
folium.GeoJson(geo_seoul).add_to(m)
m

#### 2) 경기도 행정동별 지도 geojson

In [24]:
def geojson_to_df(geojson):
    """
    행정동 geojson의 'feature'키의 'properties'키 값들로 구성된 데이터프레임
    """
    return pd.DataFrame([dong['properties'] for dong in geo_json['features']])

In [31]:
filename = 'data/geojson/행정동_경기도.geojson'

with open(filename, encoding='utf-8') as f:
    geo_gg = json.loads(f.read())

geo_gg_prop = geojson_to_df(geo_gg)
geo_gg_prop.head()

   OBJECTID           adm_nm   adm_cd     adm_cd2    sgg sido sidonm   sggnm
0      1156   경기도 수원시장안구 파장동  3101154  4111156000  41111   41    경기도  수원시장안구
1      1157   경기도 수원시장안구 율천동  3101155  4111156600  41111   41    경기도  수원시장안구
2      1158  경기도 수원시장안구 정자1동  3101156  4111157100  41111   41    경기도  수원시장안구
3      1159  경기도 수원시장안구 정자2동  3101157  4111157200  41111   41    경기도  수원시장안구
4      1160   경기도 수원시장안구 영화동  3101158  4111158000  41111   41    경기도  수원시장안구

In [30]:
geo_gg_prop.shape

(551, 8)

In [35]:
cityhall = (37.566535, 126.9779691999996)  # 서울 시청
zoom = 8
m = folium.Map(location=cityhall, zoom_start=zoom)
folium.GeoJson(geo_gg).add_to(m)
m

#### 3) 전국 행정구별 경계선 표시

In [37]:
filename = 'data/geojson/행정구별_southKorea_geo.json'
with open(filename, encoding='utf-8') as f:
    geo_kr = json.loads(f.read())

In [39]:
geo_kr.keys()

dict_keys(['type', 'features'])

In [41]:
geo_kr['features']

[{'type': 'Feature',
  'properties': {'code': '39020',
   'name': '서귀포시',
   'name_eng': 'Seogwipo-si',
   'base_year': '2013'},
  'geometry': {'type': 'Polygon',
   'coordinates': [[[126.1701670531016, 33.27833920373795],
     [126.17796199822318, 33.28904450342792],
     [126.20366562455006, 33.292582069125935],
     [126.23227804627976, 33.28054651709448],
     [126.27081469983565, 33.29305651947374],
     [126.28692516789717, 33.3095121006344],
     [126.32582807936741, 33.32307849544494],
     [126.33863040850332, 33.33700002289742],
     [126.37692773779688, 33.34348978209229],
     [126.42008790072302, 33.33448285889923],
     [126.43967991919219, 33.34042205120408],
     [126.44742456956253, 33.35529267692266],
     [126.4918716225209, 33.351283204155564],
     [126.54001194569452, 33.35949354681064],
     [126.55310458705854, 33.368769331336765],
     [126.5830715764017, 33.368027779973275],
     [126.65655971322707, 33.39658294968576],
     [126.68911351796443, 33.39691133705054],
     [126.70784071345439, 33.41819831436605],
     [126.73472429940135, 33.422146338653775],
     [126.75951968887561, 33.41497179862364],
     [126.79074582138537, 33.43825351998022],
     [126.82385785054652, 33.44338028367965],
     [126.8898274152664, 33.47823603716075],
     [126.90529687529418, 33.480086403367224],
     [126.91451306461225, 33.46996423390579],
     [126.93834260748045, 33.47055272752707],
     [126.91017277435895, 33.402610687558585],
     [126.90919306806411, 33.3879255679562],
     [126.87535882585192, 33.36822409322237],
     [126.8705501162605, 33.34975159885652],
     [126.84671810776004, 33.33005904428782],
     [126.83805963301805, 33.30541883125935],
     [126.81058128765947, 33.29810905802241],
     [126.78058721090692, 33.30348117728641],
     [126.74744517061241, 33.27477917807315],
     [126.69397491052028, 33.26589785324775],
     [126.66139509103422, 33.26764883602634],
     [126.64370899012728, 33.26176379473827],
     [126.62124671799259, 33.238001461003755],
     [126.60023270919079, 33.23253794499945],
     [126.58793276547512, 33.24078903556731],
     [126.55000275643071, 33.233994617394124],
     [126.52287888872885, 33.237410624439875],
     [126.5112182224236, 33.226741039104716],
     [126.47233571972863, 33.219241198557235],
     [126.45245786615838, 33.23676200849374],
     [126.43326944303328, 33.22862021392413],
     [126.41456422346796, 33.24077765309614],
     [126.38663415314419, 33.2281960784446],
     [126.32186188505729, 33.2348134021202],
     [126.29961093191966, 33.219470994774156],
     [126.29462959454436, 33.20325737472914],
     [126.27360444082919, 33.19065258266024],
     [126.2344607950971, 33.231192587887506],
     [126.20182608174507, 33.242644947267415],
     [126.18421578146823, 33.2556336839387],
     [126.1701670531016, 33.27833920373795]]]}},
 {'type': 'Feature',
  'properties': {'code': '39010',
   'name': '제주시',
   'name_eng': 'Jeju-si',
   'base_year': '2013'},
  'geometry': {'type': 'MultiPolygon',
   'coordinates': [[[[126.95749379080732, 33.52245641440839],
      [126.9731989684708, 33.498754077952555],
      [126.94954584507536, 33.4895447597362],
      [126.94279608187666, 33.50103054337929],
      [126.95749379080732, 33.52245641440839]]],
    [[[126.90529687529418, 33.480086403367224],
      [126.8898274152664, 33.47823603716075],
      [126.82385785054652, 33.44338028367965],
      [126.79074582138537, 33.43825351998022],
      [126.75951968887561, 33.41497179862364],
      [126.73472429940135, 33.422146338653775],
      [126.70784071345439, 33.41819831436605],
      [126.68911351796443, 33.39691133705054],
      [126.65655971322707, 33.39658294968576],
      [126.5830715764017, 33.368027779973275],
      [126.55310458705854, 33.368769331336765],
      [126.54001194569452, 33.35949354681064],
      [126.4918716225209, 33.351283204155564],
      [126.44742456956253, 33.35529267692266],
      [126.43967991919219, 33.34042205120408],
      [126.42008790072302, 33.33448285889923],
      [126.37692773779688, 33.34348978209229],
      [126.33863040850332, 33.33700002289742],
      [126.32582807936741, 33.32307849544494],
      [126.28692516789717, 33.3095121006344],
      [126.27081469983565, 33.29305651947374],
      [126.23227804627976, 33.28054651709448],
      [126.20366562455006, 33.292582069125935],
      [126.17796199822318, 33.28904450342792],
      [126.1701670531016, 33.27833920373795],
      [126.16319295942347, 33.32059642402829],
      [126.1692541537235, 33.34310558958249],
      [126.21461375807213, 33.37309156042842],
      [126.2619192214544, 33.413737972061774],
      [126.26197058380335, 33.43142547688364],
      [126.3070400569873, 33.44823091074929],
      [126.31005406486322, 33.463098336550836],
      [126.33749501698236, 33.46367421762971],
      [126.38761176138898, 33.4865145900699],
      [126.39670361974751, 33.4811364736424],
      [126.48208433034038, 33.50677622835366],
      [126.49529547568828, 33.5184121837681],
      [126.51667984271614, 33.51331402436857],
      [126.54176863235955, 33.527562476211756],
      [126.55087422195945, 33.51759024881304],
      [126.58362236141552, 33.523927713435334],
      [126.59940627536525, 33.53451980393117],
      [126.63484958960886, 33.53527429124482],
      [126.64568938881722, 33.553414822717535],
      [126.66008979414049, 33.548871831149306],
      [126.75800613842082, 33.55555170516014],
      [126.78655545465347, 33.562854180697364],
      [126.80185825451599, 33.553702356637885],
      [126.82997198815602, 33.55685083846837],
      [126.8331417008821, 33.543008206988866],
      [126.85956040111658, 33.5237459631211],
      [126.87389326759744, 33.52840985278047],
      [126.9044869524447, 33.52306487335703],
      [126.91799070617053, 33.498337310154],
      [126.90529687529418, 33.480086403367224]]]]}},
 {'type': 'Feature',
  'properties': {'code': '38400',
   'name': '합천군',
   'name_eng': 'Hapcheon-gun',
   'base_year': '2013'},
  'geometry': {'type': 'Polygon',
   'coordinates': [[[128.16624529480816, 35.77401846166936],
     [128.1664702916369, 35.75973538713466],
     [128.1894575867061, 35.751146695515],
     [128.20376038881219, 35.71979380237135],
     [128.20429067824932, 35.68136577618283],
     [128.16631648353624, 35.67023484769286],
     [128.1659217940842, 35.650471858798795],
     [128.18707873977326, 35.65477072180895],
     [128.20320925841966, 35.64077141381145],
     [128.26329705154626, 35.63966480980178],
     [128.2805996850208, 35.64872993618149],
     [128.30824855773733, 35.652120313603305],
     [128.35712252872025, 35.63944851830449],
     [128.36455141800863, 35.60886521477258],
     [128.35409802241534, 35.60371927292992],
     [128.36393478624836, 35.574975399652736],
     [128.3524935496341, 35.55000008227065],
     [128.35496578489835, 35.531894795852615],
     [128.3744422383229, 35.515918290232825],
     [128.37407817895624, 35.49890497146474],
     [128.34872680409157, 35.497321764508584],
     [128.31804497181153, 35.51223556949818],
     [128.27145497185825, 35.507959905286114],
     [128.25718580241585, 35.49069085259646],
     [128.21164046549285, 35.47987941280686],
     [128.20932135887128, 35.44514848238987],
     [128.18760031125066, 35.416098144676965],
     [128.19163963328742, 35.395600668867864],
     [128.15025100085697, 35.3829356736949],
     [128.13122380773524, 35.38470212549547],
     [128.0974979573329, 35.36509977790733],
     [128.08252050187886, 35.367071488869165],
     [128.0911919700177, 35.376295973942185],
     [128.06149064233767, 35.40249128057027],
     [128.0370495961085, 35.412354291679875],
     [127.98909413543431, 35.44239897076061],
     [127.9644438069297, 35.49708390818465],
     [127.96199110121547, 35.515544170593],
     [127.9572157884059, 35.54689130661954],
     [127.98168204634861, 35.5604840613817],
     [128.00000000005576, 35.62512172418849],
     [128.02274033148038, 35.648851589143554],
     [128.04669466251949, 35.65846299958867],
     [128.05252951106863, 35.67512928831512],
     [128.09341425381487, 35.679002127942525],
     [128.04635387023492, 35.7491552480925],
     [128.0530956577539, 35.775203641092915],
     [128.03781558941037, 35.78313812768474],
     [128.05675234917973, 35.80278899493612],
     [128.07162436990026, 35.803127367997455],
     [128.09285821427525, 35.82781190417947],
     [128.12631731840716, 35.81934758210269],
     [128.13099154092245, 35.78636777785382],
     [128.16624529480816, 35.77401846166936]]]}},
 {'type': 'Feature',
  'properties': {'code': '38390',
   'name': '거창군',
   'name_eng': 'Geochang-gun',
   'base_year': '2013'},
  'geometry': {'type': 'Polygon',
   'coordinates': [[[128.0808946019517, 35.83592789823322],
     [128.09285821427525, 35.82781190417947],
     [128.07162436990026, 35.803127367997455],
     [128.05675234917973, 35.80278899493612],
     [128.03781558941037, 35.78313812768474],
     [128.0530956577539, 35.775203641092915],
     [128.04635387023492, 35.7491552480925],
     [128.09341425381487, 35.679002127942525],
     [128.05252951106863, 35.67512928831512],
     [128.04669466251949, 35.65846299958867],
     [128.02274033148038, 35.648851589143554],
     [128.00000000005576, 35.62512172418849],
     [127.98168204634861, 35.5604840613817],
     [127.9572157884059, 35.54689130661954],
     [127.96199110121547, 35.515544170593],
     [127.92733789712166, 35.512295323871264],
     [127.90636658609272, 35.531237100923796],
     [127.88572598527269, 35.52674793116807],
     [127.87971758127198, 35.54748046711532],
     [127.8584771352235, 35.56639407905894],
     [127.83883935445412, 35.58167726997778],
     [127.8642285488878, 35.60242817105692],
     [127.87931611191121, 35.63632191323443],
     [127.87903439543761, 35.66632785604621],
     [127.85959869699167, 35.654558929921755],
     [127.84013086288222, 35.65791408945248],
     [127.80554976526314, 35.68283612565876],
     [127.78670628822648, 35.70224660574283],
     [127.75004260239912, 35.727774833190544],
     [127.73626058342799, 35.7159811280101],
     [127.71710264829723, 35.72807414799062],
     [127.71167148293574, 35.74423910588158],
     [127.68117959125036, 35.76626337169757],
     [127.701802319878, 35.78521403230135],
     [127.72169757530648, 35.794401661864065],
     [127.74771260259949, 35.840231148337296],
     [127.77430805818344, 35.835931201088876],
     [127.79002262574487, 35.84863700680608],
     [127.81086035788745, 35.850585966055256],
     [127.85367091213554, 35.88650302484426],
     [127.88977573951732, 35.911587829722514],
     [127.88702736928099, 35.8900214278366],
     [127.9181488268422, 35.88882079085176],
     [127.93266492586233, 35.87516485795083],
     [127.93452067606925, 35.85279314719248],
     [127.95300566143057, 35.85825652751344],
     [127.97345746271034, 35.84813131360324],
     [127.98754018176862, 35.85439265559927],
     [128.0143198192375, 35.825861917061715],
     [128.0337944079462, 35.832712716585775],
     [128.05301880025073, 35.82625866369297],
     [128.0808946019517, 35.83592789823322]]]}},
 {'type': 'Feature',
  'properties': {'code': '38380',
   'name': '함양군',
   'name_eng': 'Hamyang-gun',
   'base_year': '2013'},
  'geometry': {'type': 'Polygon',
   'coordinates': [[[127.68117959125036, 35.76626337169757],
     [127.71167148293574, 35.74423910588158],
     [127.71710264829723, 35.72807414799062],
     [127.73626058342799, 35.7159811280101],
     [127.75004260239912, 35.727774833190544],
     [127.78670628822648, 35.70224660574283],
     [127.80554976526314, 35.68283612565876],
     [127.84013086288222, 35.65791408945248],
     [127.85959869699167, 35.654558929921755],
     [127.87903439543761, 35.66632785604621],
     [127.87931611191121, 35.63632191323443],
     [127.8642285488878, 35.60242817105692],
     [127.83883935445412, 35.58167726997778],
     [127.8584771352235, 35.56639407905894],
     [127.82647959022646, 35.52630497499644],
     [127.82547086301373, 35.49666854384417],
     [127.80760710148745, 35.486815563144994],
     [127.81669501190471, 35.46912803212254],
     [127.78547790733566, 35.456878790474384],
     [127.79163783350509, 35.442497401264085],
     [127.74150928022797, 35.37005907056049],
     [127.73314475788736, 35.33416016437907],
     [127.7028018525535, 35.31317331334318],
     [127.69093497481566, 35.31609860653267],
     [127.64241396882525, 35.321590761582186],
     [127.62255357551241, 35.32927181793541],
     [127.62499983755144, 35.34089464357375],
     [127.61239063783061, 35.36273904340445],
     [127.64237176030026, 35.4019251607235],
     [127.66411926799725, 35.413610051109025],
     [127.6692394228911, 35.44502861676517],
     [127.64664890913163, 35.4469007356311],
     [127.6389097994206, 35.475425315441605],
     [127.6548636399853, 35.48263157109243],
     [127.62626024808586, 35.530815877858245],
     [127.58754154895051, 35.55155610121074],
     [127.59683579169358, 35.57112497612402],
     [127.61272622271566, 35.581834971793434],
     [127.61454267406016, 35.60392998899467],
     [127.63022870610416, 35.6151118326467],
     [127.62231674271511, 35.63930859338237],
     [127.64107637082431, 35.66687730924716],
     [127.64701792240557, 35.695351291284126],
     [127.66331488462136, 35.70701918782875],
     [127.6636402151408, 35.75576399105268],
     [127.68117959125036, 35.76626337169757]]]}},
 {'type': 'Feature',
  'properties': {'code': '38370',
   'name': '산청군',
   'name_eng': 'Sancheong-gun',
   'base_year': '2013'},
  'geometry': {'type': 'Polygon',
   'coordinates': [[[127.8584771352235, 35.56639407905894],
     [127.87971758127198, 35.54748046711532],
     [127.88572598527269, 35.52674793116807],
     [127.90636658609272, 35.531237100923796],
     [127.92733789712166, 35.512295323871264],
     [127.96199110121547, 35.515544170593],
     [127.9644438069297, 35.49708390818465],
     [127.98909413543431, 35.44239897076061],
     [128.0370495961085, 35.412354291679875],
     [128.06149064233767, 35.40249128057027],
     [128.0911919700177, 35.376295973942185],
     [128.08252050187886, 35.367071488869165],
     [128.0995928201349, 35.33864919262178],
     [128.11687378252063, 35.32779793427036],
     [128.08262173488154, 35.33391370725174],
     [128.06094962016707, 35.33061911871106],
     [128.0548096774713, 35.31022559201209],
     [128.01725560680936, 35.30031544184489],
     [127.98526279201724, 35.26761099826563],
     [127.96928868717279, 35.24350740576714],
     [127.9402095821842, 35.24658300150516],
     [127.91492160712303, 35.24143385644232],
     [127.91115468339237, 35.22098970008665],
     [127.8924765679516, 35.22342502039741],
     [127.89409579054586, 35.247274341381676],
     [127.86645560944062, 35.255304160081984],
     [127.85940410332486, 35.23721104278759],
     [127.82784704564068, 35.21887367004633],
     [127.77826308383216, 35.21647348488036],
     [127.75542617197208, 35.233295818740004],
     [127.751303321126, 35.24639911493246],
     [127.7071802407449, 35.26164973051596],
     [127.6926496009535, 35.28163952853893],
     [127.69093497481566, 35.31609860653267],
     [127.7028018525535, 35.31317331334318],
     [127.73314475788736, 35.33416016437907],
     [127.74150928022797, 35.37005907056049],
     [127.79163783350509, 35.442497401264085],
     [127.78547790733566, 35.456878790474384],
     [127.81669501190471, 35.46912803212254],
     [127.80760710148745, 35.486815563144994],
     [127.82547086301373, 35.49666854384417],
     [127.82647959022646, 35.52630497499644],
     [127.8584771352235, 35.56639407905894]]]}},
 {'type': 'Feature',
  'properties': {'code': '38360',
   'name': '하동군',
   'name_eng': 'Hadong-gun',
   'base_year': '2013'},
  'geometry': {'type': 'Polygon',
   'coordinates': [[[127.69093497481566, 35.31609860653267],
     [127.6926496009535, 35.28163952853893],
     [127.7071802407449, 35.26164973051596],
     [127.751303321126, 35.24639911493246],
     [127.75542617197208, 35.233295818740004],
     [127.77826308383216, 35.21647348488036],
     [127.82784704564068, 35.21887367004633],
     [127.85940410332486, 35.23721104278759],
     [127.86645560944062, 35.255304160081984],
     [127.89409579054586, 35.247274341381676],
     [127.8924765679516, 35.22342502039741],
     [127.89563261061504, 35.19381579291404],
     [127.94000431345326, 35.16662595752856],
     [127.94456433890068, 35.15251361073343],
     [127.88314215780191, 35.13647520526402],
     [127.91250585022131, 35.11684934335774],
     [127.90682590412113, 35.07637301337006],
     [127.93351349025966, 35.04470395532574],
     [127.92585088856953, 35.038786416919955],
     [127.9247121509133, 35.01094552325906],
     [127.90500405807323, 34.967183389884994],
     [127.90610345544165, 34.95522852665841],
     [127.87701666137329, 34.94379898007951],
     [127.83891427244511, 34.94650928065336],
     [127.78734616904073, 34.937095528490254],
     [127.76723341473074, 34.969692134340335],
     [127.77992174699216, 34.98501237922331],
     [127.78930306401567, 35.014156267367376],
     [127.77410976002916, 35.02639161374947],
     [127.77084118106403, 35.04735517487035],
     [127.74246434265035, 35.05887476074519],
     [127.73961183100337, 35.0750004882331],
     [127.7210162269397, 35.078548072726164],
     [127.69674169362222, 35.10000006121108],
     [127.69724601781206, 35.126683300768015],
     [127.6615250195796, 35.15527458546599],
     [127.64743915244925, 35.158229160802804],
     [127.6268774266599, 35.181418200842195],
     [127.61932122583441, 35.20700221686294],
     [127.62053090469021, 35.23414059506307],
     [127.61215751707601, 35.25884968329884],
     [127.59793454993918, 35.26509831056045],
     [127.57958308106805, 35.30590140072674],
     [127.59443183145093, 35.30847576309812],
     [127.62255357551241, 35.32927181793541],
     [127.64241396882525, 35.321590761582186],
     [127.69093497481566, 35.31609860653267]]]}},
 {'type': 'Feature',
  'properties': {'code': '38350',
   'name': '남해군',
   'name_eng': 'Namhae-gun',
   'base_year': '2013'},
  'geometry': {'type': 'MultiPolygon',
   'coordinates': [[[[128.03557300211216, 34.91641436824548],
      [128.03931841280408, 34.89545072932928],
      [128.06917275741617, 34.86722877773087],
      [128.06562117115837, 34.82722801123564],
      [128.02534613507106, 34.835937401563655],
      [127.9894367248561, 34.83329097011279],
      [127.97078317956345, 34.840451347711394],
      [127.96359226777956, 34.866629176120696],
      [127.98045276246754, 34.87698403095819],
      [128.0091773609462, 34.91644567659888],
      [128.03557300211216, 34.91641436824548]]],
    [[[127.89758139784885, 34.94331107286024],
      [127.92014425187527, 34.93650645247182],
      [127.93244296812351, 34.91149664315565],
      [127.9005492120558, 34.86947473016224],
      [127.92634960213488, 34.82755615935358],
      [127.94472880656821, 34.82345135944615],
      [127.9565427891179, 34.80213030355785],
      [127.9921741301316, 34.82992672870008],
      [128.03452049232595, 34.8273103656319],
      [128.06273380354537, 34.81875280058967],
      [128.06376769573112, 34.79633183663036],
      [128.05345691903028, 34.79170934123589],
      [128.05913146212396, 34.74228659694756],
      [128.0279828760633, 34.715819454986125],
      [128.0161250854622, 34.72084321708546],
      [127.98768060353535, 34.707882144729474],
      [127.95842450599794, 34.706331157224376],
      [127.9480697239386, 34.7295324147021],
      [127.9513223979442, 34.7741702777419],
      [127.90629936933237, 34.76255072633004],
      [127.91495413199529, 34.73316175787218],
      [127.88878431880482, 34.71866259378943],
      [127.86932132180657, 34.722973198890834],
      [127.85753329063189, 34.74042945689467],
      [127.83833555024074, 34.74718109205451],
      [127.85418474851778, 34.766144107843076],
      [127.836971482941, 34.79971439319492],
      [127.8147456550853, 34.831540949879425],
      [127.8086509816053, 34.854266562540836],

In [42]:
len(geo_kr['features'])

251

- 행정구별 전국 지도 경계 표시

In [44]:
cityhall = (37.566535, 126.9779691999996)  # 서울 시청
zoom = 8
m = folium.Map(location=cityhall, zoom_start=zoom)
folium.GeoJson(geo_kr).add_to(m)
m

----

## 9. 단계 구분도(Choropleth Map)

#### Choropleth를 활용하여 GeoJson 데이터와 결합

- **Choropleth** : 행정구역별로 다른 색상을 표현
- 행정구역 등과 같이 지도상의 어떤 경계로 구분된 지도 영역에 색을 칠하거나 음영 등을 넣어 정보를 나타낸 지도
- 데이터를 지도 그림에 반영시켜서 전달하는 그래프
- 보통 folium에 layer로 얹게 됨

- map 객체의 **choropleth()** 이용해서 작업

- 사용 인수
    - geo_data : 지도 파일 경로와 파일명
    - data : 지도에 표현되어야 할 값 변수
    - columns =  [key로 사용할 data, 실제 data의 필드명]
    - key_on : 지도 경계파일인 json에서 사용할 키 값이며 지도 Data는 표준 형식으로 만들어 져야 함
        - key_on 지칭 문법 : feature(키워드).json에서 나타나키 필드명


- folium.LayerControl().add_to(map)  : 단계구분도를 map에 표시하는 함수

```python
folium.features.Choropleth(geo_data: Any,
    data: Any | None = None,
    columns: Sequence[Any] | None = None,
    key_on: str | None = None,
    bins: int | Sequence[float] = 6,
    fill_color: str | None = None,
    nan_fill_color: str = 'black',
    fill_opacity: float = 0.6,
    nan_fill_opacity: float | None = None,
    line_color: str = 'black',
    line_weight: float = 1, line_opacity: float = 1,
    name: str | None = None,
    legend_name: str = '',
    overlay: bool = True, control: bool = True,
    show: bool = True, topojson: str | None = None,
    smooth_factor: float | None = None, highlight: bool = False,
    use_jenks: bool = False, **kwargs)
```
사용 인수
- geo_data : 시도 파일 경로와 파일명
- data : 지도에 표현되어야 할 값 변수
- columns = [key로 사용할 data, 실제 data의 필드명]
- key_on : 지도 경계파일인 json에서 사용할 키 값이며 지도 Data는 표준 형식으로 만들어 져야 함
- key_on 지칭 문법 : feature(키워드).json에서 나타내키 필드명

### 예제1.

- 미국 각 주별 2012년 10월 실업률 data
   - https://raw.githubusercontent.com/python-visualization/folium/master/examples/data/US_Unemployment_Oct2012.csv
- 지도 경계 data : .json 파일로 작성
   - https://raw.githubusercontent.com/python-visualization/folium/master/examples/data/us-states.json

In [45]:
url = 'https://raw.githubusercontent.com/python-visualization/folium/master/examples/data'
data_file = f'{url}/US_Unemployment_Oct2012.csv'
geo_file = f'{url}/us-states.json'
US_df = pd.read_csv(data_file)

US_df.head()

  State  Unemployment
0    AL           7.1
1    AK           6.8
2    AZ           8.1
3    AR           7.2
4    CA          10.1

In [47]:
US_df.head()

  State  Unemployment
0    AL           7.1
1    AK           6.8
2    AZ           8.1
3    AR           7.2
4    CA          10.1

**단계구분도를 적용한 지도 시각화**

In [57]:
cityhall = (37.566535, 126.977969199996)  # 서울 시청
zoom = 8
m = folium.Map(location=cityhall, zoom_start=zoom)

folium.GeoJson(geo_gg).add_to(m)

folium.Choropleth(
    geo_data=geo_gg,   #지도경계 구분을 위한 json
    data=pop.gg,    #지도에 표시할 데이터프레임
    columns=['State', 'Unemployment'], #지도에 표시할 data의 컬럼
    key_on='feature.id',   # geo json의 지역코드 : feature속성의 지역코드 속성 이름
    bins=7,
    fill_color='YlGn',
    fill_opacity=0.7,
    line_opacity=1,
    name='choropleth',
    legend_name='Unemployment Rate(%)',
).add_to(m)

folium.LayerControl().add_to(m)

m

### 예제2. 경기도 지역 시군구별 인구수 지도 시각화

#### 1) 경기도 행정구역 경계 지리정보 json 데이터 파일 로드
- 경기도 시군별 경계정보

- pd.read_json()을 이용하여 지도 데이터 로딩

In [89]:
file_name = 'data/geojson/경기도행정구역경계.json'
with open(file_name, encoding='utf-8') as f:
    geo_gg = json.loads(f.read())
geo_gg.keys()

dict_keys(['type', 'features'])

In [90]:
df_gg = geojson_to_df(geo_gg)
df_gg

     OBJECTID           adm_nm   adm_cd     adm_cd2    sgg sido sidonm   sggnm
0        1156   경기도 수원시장안구 파장동  3101154  4111156000  41111   41    경기도  수원시장안구
1        1157   경기도 수원시장안구 율천동  3101155  4111156600  41111   41    경기도  수원시장안구
2        1158  경기도 수원시장안구 정자1동  3101156  4111157100  41111   41    경기도  수원시장안구
3        1159  경기도 수원시장안구 정자2동  3101157  4111157200  41111   41    경기도  수원시장안구
4        1160   경기도 수원시장안구 영화동  3101158  4111158000  41111   41    경기도  수원시장안구
..        ...              ...      ...         ...    ...  ...    ...     ...
546      3487  경기도 용인시기흥구 동백1동  3119267  4146357200  41463   41    경기도  용인시기흥구
547      3488      경기도 하남시 감일동  3118067  4145058200  41450   41    경기도     하남시
548      1605      경기도 광주시 쌍령동  3125056  4161054000  41610   41    경기도     광주시
549      1606      경기도 광주시 송정동  3125055  4161052000  41610   41    경기도     광주시
550      1607     경기도 광주시 광남1동  3125058  4161056000  41610   41    경기도     광주시

[551 rows x 8 columns]

In [91]:
df_gg.columns

Index(['OBJECTID', 'adm_nm', 'adm_cd', 'adm_cd2', 'sgg', 'sido', 'sidonm',
       'sggnm'],
      dtype='str')

In [97]:
geo_gg['features'][0]

{'type': 'Feature',
 'properties': {'code': 31380,
  'name': '양평군',
  'name_eng': 'Yangpyeong-gun',
  'base_year': 2013},
 'geometry': {'type': 'Polygon',
  'coordinates': [[[127.56113535909492, 37.6256560539258],
    [127.57290963929243, 37.61087369350498],
    [127.56366973908277, 37.5842624297699],
    [127.52226606559191, 37.5828628697518],
    [127.50048767007603, 37.569036373178626],
    [127.47687473909174, 37.574448241913856],
    [127.47565866803647, 37.60512112601634],
    [127.44699730711024, 37.64497584741164],
    [127.4272349102434, 37.66284420898682],
    [127.40156700708162, 37.64806970784708],
    [127.3732642199939, 37.6453987554284],
    [127.3542931884407, 37.6250006376975],
    [127.34360057873045, 37.588997440929354],
    [127.31002843450217, 37.53523876142835],
    [127.30923294884336, 37.5135706079458],
    [127.32809611134748, 37.53133849534739],
    [127.3663244453597, 37.52716845880826],
    [127.38286320755414, 37.50147517965334],
    [127.39046783039153, 37.47413422098595],
    [127.37490698722792, 37.455072688441305],
    [127.39174400683049, 37.4256483411369],
    [127.40276739880215, 37.41856433413549],
    [127.4250053080982, 37.43669952587185],
    [127.4817900304572, 37.42084413829662],
    [127.51015267026155, 37.43699555518635],
    [127.52501209957308, 37.43192043868044],
    [127.53910572062166, 37.40849283821634],
    [127.60528700481163, 37.416969769508924],
    [127.63754040237271, 37.41065607591271],
    [127.6491838950862, 37.402042953108506],
    [127.66976823475012, 37.40884431255766],
    [127.71071536074867, 37.40736583858037],
    [127.70347417929173, 37.371054026073324],
    [127.76165381178268, 37.36421926003675],
    [127.77952402154285, 37.368441789396854],
    [127.80397287036232, 37.432516049235865],
    [127.79833492163134, 37.460500237870505],
    [127.77664798308412, 37.48883635932707],
    [127.77611527652192, 37.50328615763377],
    [127.80855972024105, 37.53220450961153],
    [127.8445769305193, 37.53621789699497],
    [127.85162286006927, 37.55037340096326],
    [127.81507964099751, 37.5618389022189],
    [127.79492564827493, 37.58252978378627],
    [127.76838776707211, 37.580178216134605],
    [127.75614914198108, 37.589477424718204],
    [127.7102810556826, 37.58360128682645],
    [127.69869383868397, 37.59757031454811],
    [127.65553070991882, 37.61954565135447],
    [127.62972032693943, 37.63983122973888],
    [127.60450569091653, 37.648548552427314],
    [127.58166701442097, 37.63033393389168],
    [127.56113535909492, 37.6256560539258]]]}}

#### 2) 경기도 시군별 경계선 지도 표시

In [65]:
cityhall = (37.566535, 126.977969199996)
zoom = 9
m = folium.Map(location=cityhall, zoom_start=zoom)
folium.GeoJson(geo_gg).add_to(m)
m

#### 3) 경기도 시군별 인구 데이터 로딩

In [116]:
filename = 'data/경기도인구데이터.xlsx'
pop_gg = pd.read_excel(filename)
pop_gg.head()

,구분,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,수원시장안구,287474,285803,290798,293692,290999,291757,300908,301196,299016,296479,293828
1,수원시권선구,310553,308177,304097,306783,321176,332633,331773,339835,351053,358393,365653
2,수원시팔달구,216945,213235,219833,216503,209772,206794,204805,203479,199180,198515,193311
3,수원시영통구,252730,260210,258421,260557,266542,289074,310671,329718,335375,340654,349836
4,성남시수정구,256744,248452,242161,241070,236123,233997,228167,223539,219531,232841,236932

In [117]:
pop_gg.set_index('구분', inplace=True)
pop_gg.head()

,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
구분,,,,,,,,,,,
수원시장안구,287474,285803,290798,293692,290999,291757,300908,301196,299016,296479,293828
수원시권선구,310553,308177,304097,306783,321176,332633,331773,339835,351053,358393,365653
수원시팔달구,216945,213235,219833,216503,209772,206794,204805,203479,199180,198515,193311
수원시영통구,252730,260210,258421,260557,266542,289074,310671,329718,335375,340654,349836
성남시수정구,256744,248452,242161,241070,236123,233997,228167,223539,219531,232841,236932

In [69]:
pop_gg.index

Index(['수원시장안구', '수원시권선구', '수원시팔달구', '수원시영통구', '성남시수정구', '성남시중원구', '성남시분당구',
       '의정부시', '안양시만안구', '안양시동안구', '부천시원미구', '부천시소사구', '부천시오정구', '광명시', '평택시',
       '동두천시', '안산시상록구', '안산시단원구', '고양시덕양구', '고양시일산동구', '고양시일산서구', '과천시',
       '구리시', '남양주시', '오산시', '시흥시', '군포시', '의왕시', '하남시', '용인시처인구', '용인시기흥구',
       '용인시수지구', '파주시', '이천시', '안성시', '김포시', '화성시', '광주시', '양주시', '포천시', '여주시',
       '연천군', '가평군', '양평군'],
      dtype='str', name='구분')

In [123]:
pop_gg_prop = geojson_to_df(pop_gg)
pop_gg2 = pop_gg.reset_index()
pop_gg2.head()

,구분,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,수원시장안구,287474,285803,290798,293692,290999,291757,300908,301196,299016,296479,293828
1,수원시권선구,310553,308177,304097,306783,321176,332633,331773,339835,351053,358393,365653
2,수원시팔달구,216945,213235,219833,216503,209772,206794,204805,203479,199180,198515,193311
3,수원시영통구,252730,260210,258421,260557,266542,289074,310671,329718,335375,340654,349836
4,성남시수정구,256744,248452,242161,241070,236123,233997,228167,223539,219531,232841,236932

#### 4) 단계 구분도 표시

- 2017년 인구수

In [108]:
#2017년도 경기도 인구수
year=2017
cityhall = (37.566535, 126.977969199996)  # 서울 시청
zoom = 12
m = folium.Map(location=cityhall, zoom_start=3)

folium.GeoJson(geo_gg).add_to(m)

folium.Choropleth(
    geo_data=geo_gg,   #지도경계 구분을 위한 json
    data=pop_gg[year],    #지도에 표시할 데이터프레임
    columns=[pop_gg.index, pop_gg[year]], #지도에 표시할 data의 컬럼
    key_on='feature.properties.name',   # geo json의 지역코드 : feature속성의 지역코드 속성 이름
    fill_color='YlGn',
    fill_opacity=0.7,
    line_opacity=0.2,
    name='choropleth',
    legend_name='Population',
    threshold_scale=[0,30000,100000,200000,300000,400000,500000,999999]
).add_to(m)

folium.LayerControl().add_to(m)

m

- 2007년 인구수

------

In [131]:
# geojson의 properties.name의 인덱스와 연결하여 사용
#2017년도 경기도 인구수
year=2007
cityhall = (37.566535, 126.977969199996)  # 서울 시청
zoom = 8
m = folium.Map(location=[48,-102], zoom_start=3)

folium.GeoJson(geo_gg).add_to(m)

folium.Choropleth(
    geo_data=geo_gg,   #지도경계 구분을 위한 json
    data=pop_gg[year],    #지도에 표시할 데이터프레임
    columns=[pop_gg.index, pop_gg[year]], #지도에 표시할 data의 컬럼
    key_on='feature.properties.name',   # geo json의 지역코드 : feature속성의 지역코드 속성 이름
    fill_color='YlGn',
    fill_opacity=0.7,
    line_opacity=0.2,
    name='choropleth',
    legend_name='Population',
    threshold_scale=[30000,100000,200000,300000,400000,500000]
).add_to(m)

folium.LayerControl().add_to(m)

m

In [132]:
# geojson의 properties.name 의 속성과 데이터프레임의 한 컬럼을 기준으로 사용할 경
year=2010
cityhall = (37.566535, 126.977969199996)  # 서울 시청
zoom = 8
m = folium.Map(cityhall, zoom_start=zoom)

folium.GeoJson(geo_gg).add_to(m)

folium.Choropleth(
    geo_data=geo_gg,   #지도경계 구분을 위한 json
    data=pop_gg2,    #지도에 표시할 데이터프레임
    columns=['구분', year], #지도에 표시할 data의 컬럼
    key_on='feature.properties.name',   # geo json의 지역코드 : feature속성의 지역코드 속성 이름
    fill_color='YlGn',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='Population',
    threshold_scale=[0, 30000,100000,200000,300000,400000,500000,999999]
).add_to(m)

folium.LayerControl().add_to(m)

m